### ISSUE TITLE
 As an imdone observer I would like a Repository to run in a different event loop so that it doesn't lock up my event loop   

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone-core#111]
### Acceptance Criteria
- [ ] Emits all events comming from repo-worker.js repo as its own
- [ ] Implements repository.js API
### Tasks
- [ ] Create tests for all events being emitted by Repository
- [ ] Add all Repository methods

----
*opened via [imdone.io](https://imdone.io) from a code comment on [0d27e3d47285bee3e59dc010d0afcfa5ba72bf29](https://github.com/imdone/imdone-core/commit/0d27e3d47285bee3e59dc010d0afcfa5ba72bf29) by Jesse jesse@piascik.net*

----

https://github.com/imdone/imdone-core/blob/3746f83fc150302d63d2322dc706dd831ae86ab0/test/repo-worker-spec.js#L9-L20
