### ISSUE TITLE
As a user I would like to add content to my TODO descriptions from markdown templates stored in my project   

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone-core#138]
- [ ] Append templates to tasks with `t:<type>` metadata in them. (e.g. `t:story`)
         - [ ] if TODO appears in a single line comment, append template with single line comment prefix and the same indentation as the TODO comment
         - [ ] If TODO appears in a multiline comment, just append template at the same indentation as the TODO comment
         - [ ] Remove `t:story` after the template has been appended to the description
      - [ ] templates.md will contain templates in the format...
       ```
       # <type>
       Any markdown for your template
       ```

----
*opened via [imdone.io](https://imdone.io) from a code comment on [657ce9e8](https://github.com/imdone/imdone-core/commit/657ce9e8) by Jesse jesse@piascik.net*

----

https://github.com/imdone/imdone-core/blob/3746f83fc150302d63d2322dc706dd831ae86ab0/docs/backlog/templates/stories.md#L9-L18
